# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8da26b8ab50bb3c1212e21dce66305c6c94e287b6d47d8d526c0fea7e1d4aba0b7ccfd63b5ef5e584d47988104d4a09ec1c5615bfb7d300248400707df783285

test:
  secret_key_base: d3af52dbe421407c4436e61a49a6732b61ac684ff87cf49cc5bd59bb454ee7ed835ebc75027f981c4e6b89de3c2c74a10285f7342d44d3075772f62e69dd86a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
